name: Build latest tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: install nodejs
        uses: actions/setup-node@v1
      
      - name: install calibre
        run: |
          brew install calibre

      - name: configue gitbook
        run: |
          npm install -g gitbook-cli          
          gitbook install
          npm install -g gitbook-summary

      - name: generate pdf file
        run: |
          book sm
          ln -s -f SUMMARY.md README.md
          gitbook pdf
          mkdir -p path/to/artifact
          cp book.pdf path/to/artifact
      
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: book.pdf
          path: path/to/artifact/book.pdf

  deploy:
    name: Release file to GitHub Release
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download file
        id: download
        uses: actions/download-artifact@v2
        with:
          name: book.pdf
          path: path/to/artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact

      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag_name: v0.1.0
          release_name: Release v0.1.0
          draft: false
          prerelease: false

      - name: Upload Asset to Release
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.id }}
          asset_path: path/to/artifact/book.pdf
          asset_name: book.pdf
          asset_content_type: application/pdf