name: Build latest tag

# on: 
#   push:
#     tags: ["v*"]
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: checkout master
        uses: actions/checkout@v2
        with:
          ref: master
      - name: install nodejs
        uses: actions/setup-node@v1
      
      - name: install calibre
        run: |
          brew install calibre

      - name: configue gitbook
        run: |
          npm install -g gitbook-cli          
          gitbook install
          npm install -g gitbook-summary

      - name: generate pdf file
        run: |
          book sm
          ln -s -f SUMMARY.md README.md
          gitbook pdf


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release PDF Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.id }}
          asset_path: book.pdf
          asset_name: book.pdf
          asset_content_type: application/pdf